# Generated by Django 4.2.4 on 2023-08-26 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("data_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ProposalCustomField",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("value_char", models.CharField(blank=True, max_length=200, null=True)),
                ("value_decimal", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "custom_field",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="proposal.customfield"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("custom_fields", models.ManyToManyField(related_name="proposals", to="proposal.proposalcustomfield")),
            ],
        ),
    ]
